# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Raihane's Blog
tagline:          'My math + thoughts blog'
url:              http://raihaen.github.io
baseurl:          /

author:
  name:           'Raihane Sidhoum'
  email:            raihane.sidhoum@hec.edu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
